<?php


namespace App\Services;


class CountryService
{
    static public function listCountryNames()
    {
        return array(
            'AF' => array('cs' => 'Afghánistán', 'en' => 'Afghanistan'),
            'AX' => array('cs' => 'Ålandy', 'en' => 'Åland Islands'),
            'AL' => array('cs' => 'Albánie', 'en' => 'Albania'),
            'DZ' => array('cs' => 'Alžírsko', 'en' => 'Algeria'),
            'AS' => array('cs' => 'Americká Samoa', 'en' => 'American Samoa'),
            'AD' => array('cs' => 'Andorra', 'en' => 'Andorra'),
            'AO' => array('cs' => 'Angola', 'en' => 'Angola'),
            'AI' => array('cs' => 'Anguilla', 'en' => 'Anguilla'),
            'AQ' => array('cs' => 'Antarktida', 'en' => 'Antarctica'),
            'AG' => array('cs' => 'Antigua a Barbuda', 'en' => 'Antigua & Barbuda'),
            'AR' => array('cs' => 'Argentina', 'en' => 'Argentina'),
            'AM' => array('cs' => 'Arménie', 'en' => 'Armenia'),
            'AW' => array('cs' => 'Aruba', 'en' => 'Aruba'),
            'AC' => array('cs' => 'Ascension', 'en' => 'Ascension Island'),
            'AU' => array('cs' => 'Austrálie', 'en' => 'Australia'),
            'AT' => array('cs' => 'Rakousko', 'en' => 'Austria'),
            'AZ' => array('cs' => 'Ázerbájdžán', 'en' => 'Azerbaijan'),
            'BS' => array('cs' => 'Bahamy', 'en' => 'Bahamas'),
            'BH' => array('cs' => 'Bahrajn', 'en' => 'Bahrain'),
            'BD' => array('cs' => 'Bangladéš', 'en' => 'Bangladesh'),
            'BB' => array('cs' => 'Barbados', 'en' => 'Barbados'),
            'BY' => array('cs' => 'Bělorusko', 'en' => 'Belarus'),
            'BE' => array('cs' => 'Belgie', 'en' => 'Belgium'),
            'BZ' => array('cs' => 'Belize', 'en' => 'Belize'),
            'BJ' => array('cs' => 'Benin', 'en' => 'Benin'),
            'BM' => array('cs' => 'Bermudy', 'en' => 'Bermuda'),
            'BT' => array('cs' => 'Bhútán', 'en' => 'Bhutan'),
            'BO' => array('cs' => 'Bolívie', 'en' => 'Bolivia'),
            'BA' => array('cs' => 'Bosna a Hercegovina', 'en' => 'Bosnia & Herzegovina'),
            'BW' => array('cs' => 'Botswana', 'en' => 'Botswana'),
            'BR' => array('cs' => 'Brazílie', 'en' => 'Brazil'),
            'IO' => array('cs' => 'Britské indickooceánské území', 'en' => 'British Indian Ocean Territory'),
            'VG' => array('cs' => 'Britské Panenské ostrovy', 'en' => 'British Virgin Islands'),
            'BN' => array('cs' => 'Brunej', 'en' => 'Brunei'),
            'BG' => array('cs' => 'Bulharsko', 'en' => 'Bulgaria'),
            'BF' => array('cs' => 'Burkina Faso', 'en' => 'Burkina Faso'),
            'BI' => array('cs' => 'Burundi', 'en' => 'Burundi'),
            'KH' => array('cs' => 'Kambodža', 'en' => 'Cambodia'),
            'CM' => array('cs' => 'Kamerun', 'en' => 'Cameroon'),
            'CA' => array('cs' => 'Kanada', 'en' => 'Canada'),
            'IC' => array('cs' => 'Kanárské ostrovy', 'en' => 'Canary Islands'),
            'CV' => array('cs' => 'Kapverdy', 'en' => 'Cape Verde'),
            'BQ' => array('cs' => 'Karibské Nizozemsko', 'en' => 'Caribbean Netherlands'),
            'KY' => array('cs' => 'Kajmanské ostrovy', 'en' => 'Cayman Islands'),
            'CF' => array('cs' => 'Středoafrická republika', 'en' => 'Central African Republic'),
            'EA' => array('cs' => 'Ceuta a Melilla', 'en' => 'Ceuta & Melilla'),
            'CC' => array('cs' => 'Kokosové ostrovy', 'en' => 'Cocos (Keeling) Islands'),
            'CO' => array('cs' => 'Kolumbie', 'en' => 'Colombia'),
            'KM' => array('cs' => 'Komory', 'en' => 'Comoros'),
            'CG' => array('cs' => 'Kongo – Brazzaville', 'en' => 'Congo - Brazzaville'),
            'CD' => array('cs' => 'Kongo – Kinshasa', 'en' => 'Congo - Kinshasa'),
            'CK' => array('cs' => 'Cookovy ostrovy', 'en' => 'Cook Islands'),
            'CR' => array('cs' => 'Kostarika', 'en' => 'Costa Rica'),
            'CI' => array('cs' => 'Pobřeží slonoviny', 'en' => 'Côte d’Ivoire'),
            'HR' => array('cs' => 'Chorvatsko', 'en' => 'Croatia'),
            'CU' => array('cs' => 'Kuba', 'en' => 'Cuba'),
            'CW' => array('cs' => 'Curaçao', 'en' => 'Curaçao'),
            'CY' => array('cs' => 'Kypr', 'en' => 'Cyprus'),
            'CZ' => array('cs' => 'Česko', 'en' => 'Czechia'),
            'DK' => array('cs' => 'Dánsko', 'en' => 'Denmark'),
            'DG' => array('cs' => 'Diego García', 'en' => 'Diego Garcia'),
            'DJ' => array('cs' => 'Džibutsko', 'en' => 'Djibouti'),
            'DM' => array('cs' => 'Dominika', 'en' => 'Dominica'),
            'DO' => array('cs' => 'Dominikánská republika', 'en' => 'Dominican Republic'),
            'EC' => array('cs' => 'Ekvádor', 'en' => 'Ecuador'),
            'EG' => array('cs' => 'Egypt', 'en' => 'Egypt'),
            'SV' => array('cs' => 'Salvador', 'en' => 'El Salvador'),
            'GQ' => array('cs' => 'Rovníková Guinea', 'en' => 'Equatorial Guinea'),
            'ER' => array('cs' => 'Eritrea', 'en' => 'Eritrea'),
            'EE' => array('cs' => 'Estonsko', 'en' => 'Estonia'),
            'SZ' => array('cs' => 'Svazijsko', 'en' => 'Eswatini'),
            'ET' => array('cs' => 'Etiopie', 'en' => 'Ethiopia'),
            'FK' => array('cs' => 'Falklandské ostrovy', 'en' => 'Falkland Islands'),
            'FO' => array('cs' => 'Faerské ostrovy', 'en' => 'Faroe Islands'),
            'FJ' => array('cs' => 'Fidži', 'en' => 'Fiji'),
            'FI' => array('cs' => 'Finsko', 'en' => 'Finland'),
            'FR' => array('cs' => 'Francie', 'en' => 'France'),
            'GF' => array('cs' => 'Francouzská Guyana', 'en' => 'French Guiana'),
            'PF' => array('cs' => 'Francouzská Polynésie', 'en' => 'French Polynesia'),
            'TF' => array('cs' => 'Francouzská jižní území', 'en' => 'French Southern Territories'),
            'GA' => array('cs' => 'Gabon', 'en' => 'Gabon'),
            'GM' => array('cs' => 'Gambie', 'en' => 'Gambia'),
            'GE' => array('cs' => 'Gruzie', 'en' => 'Georgia'),
            'DE' => array('cs' => 'Německo', 'en' => 'Germany'),
            'GH' => array('cs' => 'Ghana', 'en' => 'Ghana'),
            'GI' => array('cs' => 'Gibraltar', 'en' => 'Gibraltar'),
            'GR' => array('cs' => 'Řecko', 'en' => 'Greece'),
            'GL' => array('cs' => 'Grónsko', 'en' => 'Greenland'),
            'GD' => array('cs' => 'Grenada', 'en' => 'Grenada'),
            'GP' => array('cs' => 'Guadeloupe', 'en' => 'Guadeloupe'),
            'GU' => array('cs' => 'Guam', 'en' => 'Guam'),
            'GT' => array('cs' => 'Guatemala', 'en' => 'Guatemala'),
            'GG' => array('cs' => 'Guernsey', 'en' => 'Guernsey'),
            'GN' => array('cs' => 'Guinea', 'en' => 'Guinea'),
            'GW' => array('cs' => 'Guinea-Bissau', 'en' => 'Guinea-Bissau'),
            'GY' => array('cs' => 'Guyana', 'en' => 'Guyana'),
            'HT' => array('cs' => 'Haiti', 'en' => 'Haiti'),
            'HN' => array('cs' => 'Honduras', 'en' => 'Honduras'),
            'HK' => array('cs' => 'Hongkong – ZAO Číny', 'en' => 'Hong Kong SAR China'),
            'HU' => array('cs' => 'Maďarsko', 'en' => 'Hungary'),
            'TD' => array('cs' => 'Čad', 'en' => 'Chad'),
            'CL' => array('cs' => 'Chile', 'en' => 'Chile'),
            'CN' => array('cs' => 'Čína', 'en' => 'China'),
            'CX' => array('cs' => 'Vánoční ostrov', 'en' => 'Christmas Island'),
            'IS' => array('cs' => 'Island', 'en' => 'Iceland'),
            'IN' => array('cs' => 'Indie', 'en' => 'India'),
            'ID' => array('cs' => 'Indonésie', 'en' => 'Indonesia'),
            'IR' => array('cs' => 'Írán', 'en' => 'Iran'),
            'IQ' => array('cs' => 'Irák', 'en' => 'Iraq'),
            'IE' => array('cs' => 'Irsko', 'en' => 'Ireland'),
            'IM' => array('cs' => 'Ostrov Man', 'en' => 'Isle of Man'),
            'IL' => array('cs' => 'Izrael', 'en' => 'Israel'),
            'IT' => array('cs' => 'Itálie', 'en' => 'Italy'),
            'JM' => array('cs' => 'Jamajka', 'en' => 'Jamaica'),
            'JP' => array('cs' => 'Japonsko', 'en' => 'Japan'),
            'JE' => array('cs' => 'Jersey', 'en' => 'Jersey'),
            'JO' => array('cs' => 'Jordánsko', 'en' => 'Jordan'),
            'KZ' => array('cs' => 'Kazachstán', 'en' => 'Kazakhstan'),
            'KE' => array('cs' => 'Keňa', 'en' => 'Kenya'),
            'KI' => array('cs' => 'Kiribati', 'en' => 'Kiribati'),
            'XK' => array('cs' => 'Kosovo', 'en' => 'Kosovo'),
            'KW' => array('cs' => 'Kuvajt', 'en' => 'Kuwait'),
            'KG' => array('cs' => 'Kyrgyzstán', 'en' => 'Kyrgyzstan'),
            'LA' => array('cs' => 'Laos', 'en' => 'Laos'),
            'LV' => array('cs' => 'Lotyšsko', 'en' => 'Latvia'),
            'LB' => array('cs' => 'Libanon', 'en' => 'Lebanon'),
            'LS' => array('cs' => 'Lesotho', 'en' => 'Lesotho'),
            'LR' => array('cs' => 'Libérie', 'en' => 'Liberia'),
            'LY' => array('cs' => 'Libye', 'en' => 'Libya'),
            'LI' => array('cs' => 'Lichtenštejnsko', 'en' => 'Liechtenstein'),
            'LT' => array('cs' => 'Litva', 'en' => 'Lithuania'),
            'LU' => array('cs' => 'Lucembursko', 'en' => 'Luxembourg'),
            'MO' => array('cs' => 'Macao – ZAO Číny', 'en' => 'Macao SAR China'),
            'MG' => array('cs' => 'Madagaskar', 'en' => 'Madagascar'),
            'MW' => array('cs' => 'Malawi', 'en' => 'Malawi'),
            'MY' => array('cs' => 'Malajsie', 'en' => 'Malaysia'),
            'MV' => array('cs' => 'Maledivy', 'en' => 'Maldives'),
            'ML' => array('cs' => 'Mali', 'en' => 'Mali'),
            'MT' => array('cs' => 'Malta', 'en' => 'Malta'),
            'MH' => array('cs' => 'Marshallovy ostrovy', 'en' => 'Marshall Islands'),
            'MQ' => array('cs' => 'Martinik', 'en' => 'Martinique'),
            'MR' => array('cs' => 'Mauritánie', 'en' => 'Mauritania'),
            'MU' => array('cs' => 'Mauricius', 'en' => 'Mauritius'),
            'YT' => array('cs' => 'Mayotte', 'en' => 'Mayotte'),
            'MX' => array('cs' => 'Mexiko', 'en' => 'Mexico'),
            'FM' => array('cs' => 'Mikronésie', 'en' => 'Micronesia'),
            'MD' => array('cs' => 'Moldavsko', 'en' => 'Moldova'),
            'MC' => array('cs' => 'Monako', 'en' => 'Monaco'),
            'MN' => array('cs' => 'Mongolsko', 'en' => 'Mongolia'),
            'ME' => array('cs' => 'Černá Hora', 'en' => 'Montenegro'),
            'MS' => array('cs' => 'Montserrat', 'en' => 'Montserrat'),
            'MA' => array('cs' => 'Maroko', 'en' => 'Morocco'),
            'MZ' => array('cs' => 'Mosambik', 'en' => 'Mozambique'),
            'MM' => array('cs' => 'Myanmar (Barma)', 'en' => 'Myanmar (Burma)'),
            'NA' => array('cs' => 'Namibie', 'en' => 'Namibia'),
            'NR' => array('cs' => 'Nauru', 'en' => 'Nauru'),
            'NP' => array('cs' => 'Nepál', 'en' => 'Nepal'),
            'NL' => array('cs' => 'Nizozemsko', 'en' => 'Netherlands'),
            'NC' => array('cs' => 'Nová Kaledonie', 'en' => 'New Caledonia'),
            'NZ' => array('cs' => 'Nový Zéland', 'en' => 'New Zealand'),
            'NI' => array('cs' => 'Nikaragua', 'en' => 'Nicaragua'),
            'NE' => array('cs' => 'Niger', 'en' => 'Niger'),
            'NG' => array('cs' => 'Nigérie', 'en' => 'Nigeria'),
            'NU' => array('cs' => 'Niue', 'en' => 'Niue'),
            'NF' => array('cs' => 'Norfolk', 'en' => 'Norfolk Island'),
            'KP' => array('cs' => 'Severní Korea', 'en' => 'North Korea'),
            'MK' => array('cs' => 'Severní Makedonie', 'en' => 'North Macedonia'),
            'MP' => array('cs' => 'Severní Mariany', 'en' => 'Northern Mariana Islands'),
            'NO' => array('cs' => 'Norsko', 'en' => 'Norway'),
            'OM' => array('cs' => 'Omán', 'en' => 'Oman'),
            'PK' => array('cs' => 'Pákistán', 'en' => 'Pakistan'),
            'PW' => array('cs' => 'Palau', 'en' => 'Palau'),
            'PS' => array('cs' => 'Palestinská území', 'en' => 'Palestinian Territories'),
            'PA' => array('cs' => 'Panama', 'en' => 'Panama'),
            'PG' => array('cs' => 'Papua-Nová Guinea', 'en' => 'Papua New Guinea'),
            'PY' => array('cs' => 'Paraguay', 'en' => 'Paraguay'),
            'PE' => array('cs' => 'Peru', 'en' => 'Peru'),
            'PH' => array('cs' => 'Filipíny', 'en' => 'Philippines'),
            'PN' => array('cs' => 'Pitcairnovy ostrovy', 'en' => 'Pitcairn Islands'),
            'PL' => array('cs' => 'Polsko', 'en' => 'Poland'),
            'PT' => array('cs' => 'Portugalsko', 'en' => 'Portugal'),
            'PR' => array('cs' => 'Portoriko', 'en' => 'Puerto Rico'),
            'QA' => array('cs' => 'Katar', 'en' => 'Qatar'),
            'RE' => array('cs' => 'Réunion', 'en' => 'Réunion'),
            'RO' => array('cs' => 'Rumunsko', 'en' => 'Romania'),
            'RU' => array('cs' => 'Rusko', 'en' => 'Russia'),
            'RW' => array('cs' => 'Rwanda', 'en' => 'Rwanda'),
            'WS' => array('cs' => 'Samoa', 'en' => 'Samoa'),
            'SM' => array('cs' => 'San Marino', 'en' => 'San Marino'),
            'ST' => array('cs' => 'Svatý Tomáš a Princův ostrov', 'en' => 'São Tomé & Príncipe'),
            'SA' => array('cs' => 'Saúdská Arábie', 'en' => 'Saudi Arabia'),
            'SN' => array('cs' => 'Senegal', 'en' => 'Senegal'),
            'RS' => array('cs' => 'Srbsko', 'en' => 'Serbia'),
            'SC' => array('cs' => 'Seychely', 'en' => 'Seychelles'),
            'SL' => array('cs' => 'Sierra Leone', 'en' => 'Sierra Leone'),
            'SG' => array('cs' => 'Singapur', 'en' => 'Singapore'),
            'SX' => array('cs' => 'Svatý Martin (Nizozemsko)', 'en' => 'Sint Maarten'),
            'SK' => array('cs' => 'Slovensko', 'en' => 'Slovakia'),
            'SI' => array('cs' => 'Slovinsko', 'en' => 'Slovenia'),
            'SB' => array('cs' => 'Šalamounovy ostrovy', 'en' => 'Solomon Islands'),
            'SO' => array('cs' => 'Somálsko', 'en' => 'Somalia'),
            'ZA' => array('cs' => 'Jihoafrická republika', 'en' => 'South Africa'),
            'GS' => array('cs' => 'Jižní Georgie a Jižní Sandwichovy ostrovy', 'en' => 'South Georgia & South Sandwich Islands'),
            'KR' => array('cs' => 'Jižní Korea', 'en' => 'South Korea'),
            'SS' => array('cs' => 'Jižní Súdán', 'en' => 'South Sudan'),
            'ES' => array('cs' => 'Španělsko', 'en' => 'Spain'),
            'LK' => array('cs' => 'Srí Lanka', 'en' => 'Sri Lanka'),
            'BL' => array('cs' => 'Svatý Bartoloměj', 'en' => 'St. Barthélemy'),
            'SH' => array('cs' => 'Svatá Helena', 'en' => 'St. Helena'),
            'KN' => array('cs' => 'Svatý Kryštof a Nevis', 'en' => 'St. Kitts & Nevis'),
            'LC' => array('cs' => 'Svatá Lucie', 'en' => 'St. Lucia'),
            'MF' => array('cs' => 'Svatý Martin (Francie)', 'en' => 'St. Martin'),
            'PM' => array('cs' => 'Saint-Pierre a Miquelon', 'en' => 'St. Pierre & Miquelon'),
            'VC' => array('cs' => 'Svatý Vincenc a Grenadiny', 'en' => 'St. Vincent & Grenadines'),
            'SD' => array('cs' => 'Súdán', 'en' => 'Sudan'),
            'SR' => array('cs' => 'Surinam', 'en' => 'Suriname'),
            'SJ' => array('cs' => 'Špicberky a Jan Mayen', 'en' => 'Svalbard & Jan Mayen'),
            'SE' => array('cs' => 'Švédsko', 'en' => 'Sweden'),
            'CH' => array('cs' => 'Švýcarsko', 'en' => 'Switzerland'),
            'SY' => array('cs' => 'Sýrie', 'en' => 'Syria'),
            'TW' => array('cs' => 'Tchaj-wan', 'en' => 'Taiwan'),
            'TJ' => array('cs' => 'Tádžikistán', 'en' => 'Tajikistan'),
            'TZ' => array('cs' => 'Tanzanie', 'en' => 'Tanzania'),
            'TH' => array('cs' => 'Thajsko', 'en' => 'Thailand'),
            'TL' => array('cs' => 'Východní Timor', 'en' => 'Timor-Leste'),
            'TG' => array('cs' => 'Togo', 'en' => 'Togo'),
            'TK' => array('cs' => 'Tokelau', 'en' => 'Tokelau'),
            'TO' => array('cs' => 'Tonga', 'en' => 'Tonga'),
            'TT' => array('cs' => 'Trinidad a Tobago', 'en' => 'Trinidad & Tobago'),
            'TA' => array('cs' => 'Tristan da Cunha', 'en' => 'Tristan da Cunha'),
            'TN' => array('cs' => 'Tunisko', 'en' => 'Tunisia'),
            'TR' => array('cs' => 'Turecko', 'en' => 'Turkey'),
            'TM' => array('cs' => 'Turkmenistán', 'en' => 'Turkmenistan'),
            'TC' => array('cs' => 'Turks a Caicos', 'en' => 'Turks & Caicos Islands'),
            'TV' => array('cs' => 'Tuvalu', 'en' => 'Tuvalu'),
            'UM' => array('cs' => 'Menší odlehlé ostrovy USA', 'en' => 'U.S. Outlying Islands'),
            'VI' => array('cs' => 'Americké Panenské ostrovy', 'en' => 'U.S. Virgin Islands'),
            'UG' => array('cs' => 'Uganda', 'en' => 'Uganda'),
            'UA' => array('cs' => 'Ukrajina', 'en' => 'Ukraine'),
            'AE' => array('cs' => 'Spojené arabské emiráty', 'en' => 'United Arab Emirates'),
            'GB' => array('cs' => 'Spojené království', 'en' => 'United Kingdom'),
            'US' => array('cs' => 'Spojené státy', 'en' => 'United States'),
            'UY' => array('cs' => 'Uruguay', 'en' => 'Uruguay'),
            'UZ' => array('cs' => 'Uzbekistán', 'en' => 'Uzbekistan'),
            'VU' => array('cs' => 'Vanuatu', 'en' => 'Vanuatu'),
            'VA' => array('cs' => 'Vatikán', 'en' => 'Vatican City'),
            'VE' => array('cs' => 'Venezuela', 'en' => 'Venezuela'),
            'VN' => array('cs' => 'Vietnam', 'en' => 'Vietnam'),
            'WF' => array('cs' => 'Wallis a Futuna', 'en' => 'Wallis & Futuna'),
            'EH' => array('cs' => 'Západní Sahara', 'en' => 'Western Sahara'),
            'YE' => array('cs' => 'Jemen', 'en' => 'Yemen'),
            'ZM' => array('cs' => 'Zambie', 'en' => 'Zambia'),
            'ZW' => array('cs' => 'Zimbabwe', 'en' => 'Zimbabwe')
        );
    }

    static public function listCzechCountryNames()
    {
        return array (
            'AF' => 'Afghánistán',
            'AX' => 'Ålandy',
            'AL' => 'Albánie',
            'DZ' => 'Alžírsko',
            'AS' => 'Americká Samoa',
            'VI' => 'Americké Panenské ostrovy',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarktida',
            'AG' => 'Antigua a Barbuda',
            'AR' => 'Argentina',
            'AM' => 'Arménie',
            'AW' => 'Aruba',
            'AC' => 'Ascension',
            'AU' => 'Austrálie',
            'AZ' => 'Ázerbájdžán',
            'BS' => 'Bahamy',
            'BH' => 'Bahrajn',
            'BD' => 'Bangladéš',
            'BB' => 'Barbados',
            'BE' => 'Belgie',
            'BZ' => 'Belize',
            'BY' => 'Bělorusko',
            'BJ' => 'Benin',
            'BM' => 'Bermudy',
            'BT' => 'Bhútán',
            'BO' => 'Bolívie',
            'BA' => 'Bosna a Hercegovina',
            'BW' => 'Botswana',
            'BR' => 'Brazílie',
            'IO' => 'Britské indickooceánské území',
            'VG' => 'Britské Panenské ostrovy',
            'BN' => 'Brunej',
            'BG' => 'Bulharsko',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'EA' => 'Ceuta a Melilla',
            'CK' => 'Cookovy ostrovy',
            'CW' => 'Curaçao',
            'TD' => 'Čad',
            'ME' => 'Černá Hora',
            'CZ' => 'Česko',
            'CN' => 'Čína',
            'DK' => 'Dánsko',
            'DG' => 'Diego García',
            'DM' => 'Dominika',
            'DO' => 'Dominikánská republika',
            'DJ' => 'Džibutsko',
            'EG' => 'Egypt',
            'EC' => 'Ekvádor',
            'ER' => 'Eritrea',
            'EE' => 'Estonsko',
            'ET' => 'Etiopie',
            'FO' => 'Faerské ostrovy',
            'FK' => 'Falklandské ostrovy',
            'FJ' => 'Fidži',
            'PH' => 'Filipíny',
            'FI' => 'Finsko',
            'FR' => 'Francie',
            'GF' => 'Francouzská Guyana',
            'TF' => 'Francouzská jižní území',
            'PF' => 'Francouzská Polynésie',
            'GA' => 'Gabon',
            'GM' => 'Gambie',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GD' => 'Grenada',
            'GL' => 'Grónsko',
            'GE' => 'Gruzie',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HN' => 'Honduras',
            'HK' => 'Hongkong – ZAO Číny',
            'CL' => 'Chile',
            'HR' => 'Chorvatsko',
            'IN' => 'Indie',
            'ID' => 'Indonésie',
            'IQ' => 'Irák',
            'IR' => 'Írán',
            'IE' => 'Irsko',
            'IS' => 'Island',
            'IT' => 'Itálie',
            'IL' => 'Izrael',
            'JM' => 'Jamajka',
            'JP' => 'Japonsko',
            'YE' => 'Jemen',
            'JE' => 'Jersey',
            'ZA' => 'Jihoafrická republika',
            'GS' => 'Jižní Georgie a Jižní Sandwichovy ostrovy',
            'KR' => 'Jižní Korea',
            'SS' => 'Jižní Súdán',
            'JO' => 'Jordánsko',
            'KY' => 'Kajmanské ostrovy',
            'KH' => 'Kambodža',
            'CM' => 'Kamerun',
            'CA' => 'Kanada',
            'IC' => 'Kanárské ostrovy',
            'CV' => 'Kapverdy',
            'BQ' => 'Karibské Nizozemsko',
            'QA' => 'Katar',
            'KZ' => 'Kazachstán',
            'KE' => 'Keňa',
            'KI' => 'Kiribati',
            'CC' => 'Kokosové ostrovy',
            'CO' => 'Kolumbie',
            'KM' => 'Komory',
            'CG' => 'Kongo – Brazzaville',
            'CD' => 'Kongo – Kinshasa',
            'XK' => 'Kosovo',
            'CR' => 'Kostarika',
            'CU' => 'Kuba',
            'KW' => 'Kuvajt',
            'CY' => 'Kypr',
            'KG' => 'Kyrgyzstán',
            'LA' => 'Laos',
            'LS' => 'Lesotho',
            'LB' => 'Libanon',
            'LR' => 'Libérie',
            'LY' => 'Libye',
            'LI' => 'Lichtenštejnsko',
            'LT' => 'Litva',
            'LV' => 'Lotyšsko',
            'LU' => 'Lucembursko',
            'MO' => 'Macao – ZAO Číny',
            'MG' => 'Madagaskar',
            'HU' => 'Maďarsko',
            'MY' => 'Malajsie',
            'MW' => 'Malawi',
            'MV' => 'Maledivy',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MA' => 'Maroko',
            'MH' => 'Marshallovy ostrovy',
            'MQ' => 'Martinik',
            'MU' => 'Mauricius',
            'MR' => 'Mauritánie',
            'YT' => 'Mayotte',
            'UM' => 'Menší odlehlé ostrovy USA',
            'MX' => 'Mexiko',
            'FM' => 'Mikronésie',
            'MD' => 'Moldavsko',
            'MC' => 'Monako',
            'MN' => 'Mongolsko',
            'MS' => 'Montserrat',
            'MZ' => 'Mosambik',
            'MM' => 'Myanmar (Barma)',
            'NA' => 'Namibie',
            'NR' => 'Nauru',
            'DE' => 'Německo',
            'NP' => 'Nepál',
            'NE' => 'Niger',
            'NG' => 'Nigérie',
            'NI' => 'Nikaragua',
            'NU' => 'Niue',
            'NL' => 'Nizozemsko',
            'NF' => 'Norfolk',
            'NO' => 'Norsko',
            'NC' => 'Nová Kaledonie',
            'NZ' => 'Nový Zéland',
            'OM' => 'Omán',
            'IM' => 'Ostrov Man',
            'PK' => 'Pákistán',
            'PW' => 'Palau',
            'PS' => 'Palestinská území',
            'PA' => 'Panama',
            'PG' => 'Papua-Nová Guinea',
            'PY' => 'Paraguay',
            'PE' => 'Peru',
            'PN' => 'Pitcairnovy ostrovy',
            'CI' => 'Pobřeží slonoviny',
            'PL' => 'Polsko',
            'PR' => 'Portoriko',
            'PT' => 'Portugalsko',
            'AT' => 'Rakousko',
            'RE' => 'Réunion',
            'GQ' => 'Rovníková Guinea',
            'RO' => 'Rumunsko',
            'RU' => 'Rusko',
            'RW' => 'Rwanda',
            'GR' => 'Řecko',
            'PM' => 'Saint-Pierre a Miquelon',
            'SV' => 'Salvador',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'SA' => 'Saúdská Arábie',
            'SN' => 'Senegal',
            'KP' => 'Severní Korea',
            'MK' => 'Severní Makedonie',
            'MP' => 'Severní Mariany',
            'SC' => 'Seychely',
            'SL' => 'Sierra Leone',
            'XA' => 'simulovaná diakritika',
            'XB' => 'simulovaný obousměrný zápis',
            'SG' => 'Singapur',
            'SK' => 'Slovensko',
            'SI' => 'Slovinsko',
            'SO' => 'Somálsko',
            'AE' => 'Spojené arabské emiráty',
            'GB' => 'Spojené království',
            'US' => 'Spojené státy',
            'RS' => 'Srbsko',
            'LK' => 'Srí Lanka',
            'CF' => 'Středoafrická republika',
            'SD' => 'Súdán',
            'SR' => 'Surinam',
            'SH' => 'Svatá Helena',
            'LC' => 'Svatá Lucie',
            'BL' => 'Svatý Bartoloměj',
            'KN' => 'Svatý Kryštof a Nevis',
            'MF' => 'Svatý Martin (Francie)',
            'SX' => 'Svatý Martin (Nizozemsko)',
            'ST' => 'Svatý Tomáš a Princův ostrov',
            'VC' => 'Svatý Vincenc a Grenadiny',
            'SZ' => 'Svazijsko',
            'SY' => 'Sýrie',
            'SB' => 'Šalamounovy ostrovy',
            'ES' => 'Španělsko',
            'SJ' => 'Špicberky a Jan Mayen',
            'SE' => 'Švédsko',
            'CH' => 'Švýcarsko',
            'TJ' => 'Tádžikistán',
            'TZ' => 'Tanzanie',
            'TH' => 'Thajsko',
            'TW' => 'Tchaj-wan',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad a Tobago',
            'TA' => 'Tristan da Cunha',
            'TN' => 'Tunisko',
            'TR' => 'Turecko',
            'TM' => 'Turkmenistán',
            'TC' => 'Turks a Caicos',
            'TV' => 'Tuvalu',
            'UG' => 'Uganda',
            'UA' => 'Ukrajina',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistán',
            'CX' => 'Vánoční ostrov',
            'VU' => 'Vanuatu',
            'VA' => 'Vatikán',
            'VE' => 'Venezuela',
            'VN' => 'Vietnam',
            'TL' => 'Východní Timor',
            'WF' => 'Wallis a Futuna',
            'ZM' => 'Zambie',
            'EH' => 'Západní Sahara',
            'ZW' => 'Zimbabwe'
        );
    }

    static public function listEnglishCountryNames()
    {
        return array(
            'AF' => 'Afghanistan',
            'AX' => 'Åland Islands',
            'AL' => 'Albania',
            'DZ' => 'Algeria',
            'AS' => 'American Samoa',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarctica',
            'AG' => 'Antigua & Barbuda',
            'AR' => 'Argentina',
            'AM' => 'Armenia',
            'AW' => 'Aruba',
            'AC' => 'Ascension Island',
            'AU' => 'Australia',
            'AT' => 'Austria',
            'AZ' => 'Azerbaijan',
            'BS' => 'Bahamas',
            'BH' => 'Bahrain',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Belarus',
            'BE' => 'Belgium',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BM' => 'Bermuda',
            'BT' => 'Bhutan',
            'BO' => 'Bolivia',
            'BA' => 'Bosnia & Herzegovina',
            'BW' => 'Botswana',
            'BR' => 'Brazil',
            'IO' => 'British Indian Ocean Territory',
            'VG' => 'British Virgin Islands',
            'BN' => 'Brunei',
            'BG' => 'Bulgaria',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'KH' => 'Cambodia',
            'CM' => 'Cameroon',
            'CA' => 'Canada',
            'IC' => 'Canary Islands',
            'CV' => 'Cape Verde',
            'BQ' => 'Caribbean Netherlands',
            'KY' => 'Cayman Islands',
            'CF' => 'Central African Republic',
            'EA' => 'Ceuta & Melilla',
            'TD' => 'Chad',
            'CL' => 'Chile',
            'CN' => 'China',
            'CX' => 'Christmas Island',
            'CC' => 'Cocos (Keeling) Islands',
            'CO' => 'Colombia',
            'KM' => 'Comoros',
            'CG' => 'Congo - Brazzaville',
            'CD' => 'Congo - Kinshasa',
            'CK' => 'Cook Islands',
            'CR' => 'Costa Rica',
            'CI' => 'Côte d’Ivoire',
            'HR' => 'Croatia',
            'CU' => 'Cuba',
            'CW' => 'Curaçao',
            'CY' => 'Cyprus',
            'CZ' => 'Czechia',
            'DK' => 'Denmark',
            'DG' => 'Diego Garcia',
            'DJ' => 'Djibouti',
            'DM' => 'Dominica',
            'DO' => 'Dominican Republic',
            'EC' => 'Ecuador',
            'EG' => 'Egypt',
            'SV' => 'El Salvador',
            'GQ' => 'Equatorial Guinea',
            'ER' => 'Eritrea',
            'EE' => 'Estonia',
            'SZ' => 'Eswatini',
            'ET' => 'Ethiopia',
            'FK' => 'Falkland Islands',
            'FO' => 'Faroe Islands',
            'FJ' => 'Fiji',
            'FI' => 'Finland',
            'FR' => 'France',
            'GF' => 'French Guiana',
            'PF' => 'French Polynesia',
            'TF' => 'French Southern Territories',
            'GA' => 'Gabon',
            'GM' => 'Gambia',
            'GE' => 'Georgia',
            'DE' => 'Germany',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GR' => 'Greece',
            'GL' => 'Greenland',
            'GD' => 'Grenada',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong SAR China',
            'HU' => 'Hungary',
            'IS' => 'Iceland',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'IR' => 'Iran',
            'IQ' => 'Iraq',
            'IE' => 'Ireland',
            'IM' => 'Isle of Man',
            'IL' => 'Israel',
            'IT' => 'Italy',
            'JM' => 'Jamaica',
            'JP' => 'Japan',
            'JE' => 'Jersey',
            'JO' => 'Jordan',
            'KZ' => 'Kazakhstan',
            'KE' => 'Kenya',
            'KI' => 'Kiribati',
            'XK' => 'Kosovo',
            'KW' => 'Kuwait',
            'KG' => 'Kyrgyzstan',
            'LA' => 'Laos',
            'LV' => 'Latvia',
            'LB' => 'Lebanon',
            'LS' => 'Lesotho',
            'LR' => 'Liberia',
            'LY' => 'Libya',
            'LI' => 'Liechtenstein',
            'LT' => 'Lithuania',
            'LU' => 'Luxembourg',
            'MO' => 'Macao SAR China',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malaysia',
            'MV' => 'Maldives',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MH' => 'Marshall Islands',
            'MQ' => 'Martinique',
            'MR' => 'Mauritania',
            'MU' => 'Mauritius',
            'YT' => 'Mayotte',
            'MX' => 'Mexico',
            'FM' => 'Micronesia',
            'MD' => 'Moldova',
            'MC' => 'Monaco',
            'MN' => 'Mongolia',
            'ME' => 'Montenegro',
            'MS' => 'Montserrat',
            'MA' => 'Morocco',
            'MZ' => 'Mozambique',
            'MM' => 'Myanmar (Burma)',
            'NA' => 'Namibia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NL' => 'Netherlands',
            'NC' => 'New Caledonia',
            'NZ' => 'New Zealand',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NU' => 'Niue',
            'NF' => 'Norfolk Island',
            'KP' => 'North Korea',
            'MK' => 'North Macedonia',
            'MP' => 'Northern Mariana Islands',
            'NO' => 'Norway',
            'OM' => 'Oman',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PS' => 'Palestinian Territories',
            'PA' => 'Panama',
            'PG' => 'Papua New Guinea',
            'PY' => 'Paraguay',
            'PE' => 'Peru',
            'PH' => 'Philippines',
            'PN' => 'Pitcairn Islands',
            'PL' => 'Poland',
            'PT' => 'Portugal',
            'XA' => 'Pseudo-Accents',
            'XB' => 'Pseudo-Bidi',
            'PR' => 'Puerto Rico',
            'QA' => 'Qatar',
            'RE' => 'Réunion',
            'RO' => 'Romania',
            'RU' => 'Russia',
            'RW' => 'Rwanda',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'ST' => 'São Tomé & Príncipe',
            'SA' => 'Saudi Arabia',
            'SN' => 'Senegal',
            'RS' => 'Serbia',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapore',
            'SX' => 'Sint Maarten',
            'SK' => 'Slovakia',
            'SI' => 'Slovenia',
            'SB' => 'Solomon Islands',
            'SO' => 'Somalia',
            'ZA' => 'South Africa',
            'GS' => 'South Georgia & South Sandwich Islands',
            'KR' => 'South Korea',
            'SS' => 'South Sudan',
            'ES' => 'Spain',
            'LK' => 'Sri Lanka',
            'BL' => 'St. Barthélemy',
            'SH' => 'St. Helena',
            'KN' => 'St. Kitts & Nevis',
            'LC' => 'St. Lucia',
            'MF' => 'St. Martin',
            'PM' => 'St. Pierre & Miquelon',
            'VC' => 'St. Vincent & Grenadines',
            'SD' => 'Sudan',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard & Jan Mayen',
            'SE' => 'Sweden',
            'CH' => 'Switzerland',
            'SY' => 'Syria',
            'TW' => 'Taiwan',
            'TJ' => 'Tajikistan',
            'TZ' => 'Tanzania',
            'TH' => 'Thailand',
            'TL' => 'Timor-Leste',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad & Tobago',
            'TA' => 'Tristan da Cunha',
            'TN' => 'Tunisia',
            'TR' => 'Turkey',
            'TM' => 'Turkmenistan',
            'TC' => 'Turks & Caicos Islands',
            'TV' => 'Tuvalu',
            'UM' => 'U.S. Outlying Islands',
            'VI' => 'U.S. Virgin Islands',
            'UG' => 'Uganda',
            'UA' => 'Ukraine',
            'AE' => 'United Arab Emirates',
            'GB' => 'United Kingdom',
            'US' => 'United States',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistan',
            'VU' => 'Vanuatu',
            'VA' => 'Vatican City',
            'VE' => 'Venezuela',
            'VN' => 'Vietnam',
            'WF' => 'Wallis & Futuna',
            'EH' => 'Western Sahara',
            'YE' => 'Yemen',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabwe',
        );
    }

}